### ISSUE TITLE
Using wstx-asl-3.2.9, 4.0.6, CxIdTest fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [TIBCOSoftware/genxdm#1]
```
In the "test" dependencies for the bridge-cx project, add wstx-asl.

Then try running "mvn install" on the bridge/cx project.

The CxIdTest test fails.

Here's the Maven pom.xml change.

  <dependency>
    <groupId>org.codehaus.woodstox</groupId>
    <artifactId>wstx-asl</artifactId>
    <version>4.0.6</version>
    <scope>test</scope>
  </dependency>

It doesn't matter whether you run this test under JDK 1.5 or 1.6.
```

Original issue reported on code.google.com by `aale...@gmail.com` on 12 Oct 2010 at 4:24

**Comment by aaletal** [comment]
Closing as wontfix. It was true, once upon a time, but that was against Woodstox 4.0 (current is 4.2), six years ago. If it's still happening in current woodstox, perhaps we should reopen, but it was also reported against them because it was broken there. So closing (partly because we haven't needed it in six years, apart from that it isn't really our defect).
